/**
 * list of state type
 */
const types = {
    LOAD_STORE: 'LOAD_STORE',
    STORE_RECEIVED: 'STORE_RECEIVED',
    ADD_STORE: 'ADD_STORE',
    LOAD_SINGLE_STORE: 'LOAD_SINGLE_STORE',
    SINGLE_STORE_RECEIVED: 'SINGLE_STORE_RECEIVED',
    UPDATE_STORE: 'UPDATE_STORE',
    DELETE_STORE: 'DELETE_STORE',
    SEARCH_STORE: 'SEARCH_STORE'
}

export default types;